-- MySQL Script generated by MySQL Workbench
-- 04/03/16 21:41:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tcc` DEFAULT CHARACTER SET utf8 ;
USE `tcc` ;

-- -----------------------------------------------------
-- Table `tcc`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pessoa` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(255) NULL DEFAULT NULL,
  `DataCadastro` DATETIME NULL DEFAULT NULL,
  `Ativo` TINYINT(1) NULL DEFAULT NULL,
  `UF` INT(11) NULL DEFAULT NULL,
  `Cidade` VARCHAR(255) NULL DEFAULT NULL,
  `Bairro` VARCHAR(255) NULL DEFAULT NULL,
  `Cep` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`pessoafisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pessoafisica` (
  `Pessoa_id` INT(11) NOT NULL,
  `DataNascimento` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`Pessoa_id`),
  INDEX `Pessoa_id` (`Pessoa_id` ASC),
  CONSTRAINT `FKC5C048FEEAADDB02`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `tcc`.`pessoa` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`pessoajuridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`pessoajuridica` (
  `Pessoa_id` INT(11) NOT NULL,
  `CNPJ` VARCHAR(255) NULL DEFAULT NULL,
  `RazaoSocial` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Pessoa_id`),
  INDEX `Pessoa_id` (`Pessoa_id` ASC),
  CONSTRAINT `FKB4F7BA74EAADDB02`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `tcc`.`pessoa` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`usuario` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `DataAprovacao` DATETIME NULL DEFAULT NULL,
  `IsNovo` TINYINT(1) NULL DEFAULT NULL,
  `EMail` VARCHAR(255) NULL DEFAULT NULL,
  `Login` VARCHAR(255) NULL DEFAULT NULL,
  `Senha` VARCHAR(255) NULL DEFAULT NULL,
  `FotoPerfil` LONGBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`autor` (
  `PessoaFisica_id` INT(11) NOT NULL,
  `Empresa_id` INT(11) NULL DEFAULT NULL,
  `Usuario_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PessoaFisica_id`),
  INDEX `PessoaFisica_id` (`PessoaFisica_id` ASC),
  INDEX `Empresa_id` (`Empresa_id` ASC),
  CONSTRAINT `FK8B257FBD2344FDFA`
    FOREIGN KEY (`PessoaFisica_id`)
    REFERENCES `tcc`.`pessoafisica` (`Pessoa_id`),
  CONSTRAINT `FK8B257FBD34891D33`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `tcc`.`pessoajuridica` (`Pessoa_id`),
  CONSTRAINT `FK8B257FBD7E0BBC49`
    FOREIGN KEY ()
    REFERENCES `tcc`.`usuario` ())
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`receita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`receita` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(255) NULL DEFAULT NULL,
  `Conteudo` VARCHAR(255) NULL DEFAULT NULL,
  `Data` DATETIME NULL DEFAULT NULL,
  `Audiencia` INT(11) NULL DEFAULT NULL,
  `Destaque` TINYINT(1) NULL DEFAULT NULL,
  `Status` INT(11) NULL DEFAULT NULL,
  `Autor_id` INT(11) NULL DEFAULT NULL,
  `Parente_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Autor_id` (`Autor_id` ASC),
  CONSTRAINT `FKF6428EF137BC8E7C`
    FOREIGN KEY (`Autor_id`)
    REFERENCES `tcc`.`autor` (`PessoaFisica_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`avaliacao` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `DataAvaliacao` DATETIME NULL DEFAULT NULL,
  `Nivel` INT(11) NULL DEFAULT NULL,
  `Avaliador_id` INT(11) NULL DEFAULT NULL,
  `Receita_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Avaliador_id` (`Avaliador_id` ASC),
  INDEX `Receita_id` (`Receita_id` ASC),
  CONSTRAINT `FKD77AE17B2D2125C7`
    FOREIGN KEY (`Avaliador_id`)
    REFERENCES `tcc`.`usuario` (`Id`),
  CONSTRAINT `FKD77AE17B99503128`
    FOREIGN KEY (`Receita_id`)
    REFERENCES `tcc`.`receita` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`categoria` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Valor` VARCHAR(255) NULL DEFAULT NULL,
  `Receita_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Receita_id` (`Receita_id` ASC),
  CONSTRAINT `FKB52F7E6999503128`
    FOREIGN KEY (`Receita_id`)
    REFERENCES `tcc`.`receita` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`comentario` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Data` DATETIME NULL DEFAULT NULL,
  `Conteudo` VARCHAR(255) NULL DEFAULT NULL,
  `Autor_id` INT(11) NULL DEFAULT NULL,
  `Receita_id` INT(11) NULL DEFAULT NULL,
  `Parente_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Autor_id` (`Autor_id` ASC),
  INDEX `Receita_id` (`Receita_id` ASC),
  CONSTRAINT `FK1C6859AB2494733D`
    FOREIGN KEY (`Autor_id`)
    REFERENCES `tcc`.`usuario` (`Id`),
  CONSTRAINT `FK1C6859AB99503128`
    FOREIGN KEY (`Receita_id`)
    REFERENCES `tcc`.`receita` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`funcionario` (
  `PessoaFisica_id` INT(11) NOT NULL,
  `CPF` VARCHAR(255) NULL DEFAULT NULL,
  `TipoFuncionario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`PessoaFisica_id`),
  INDEX `PessoaFisica_id` (`PessoaFisica_id` ASC),
  CONSTRAINT `FKE1699EBB2344FDFA`
    FOREIGN KEY (`PessoaFisica_id`)
    REFERENCES `tcc`.`pessoafisica` (`Pessoa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tcc`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tcc`.`telefone` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Value` VARCHAR(255) NULL DEFAULT NULL,
  `Pessoa_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `Pessoa_id` (`Pessoa_id` ASC),
  CONSTRAINT `FKC40561A0EAADDB02`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `tcc`.`pessoa` (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
